<?php

$faculty = array(

	array(
		'name' => 'Paul Barolsky',
		'title' => 'Commonwealth Professor',
		'area' => 'Italian Renaissance Art and Literature',
		'school' => 'PhD Harvard University, 1969',
		'email' => 'pb4r@virginia.edu',
		'bio' => '<p>Details from the early years of Paul Barolsky remain obscure.  We know however that he has been teaching courses on Italian Renaissance art and literature at the University of Virginia since 1969.  His books include Michelangelo\'s Nose, Why Mona Lisa Smiles, Infinite Jest, Michelangelo and the Finger of God, and A Brief History of the Artist from God to Picasso.</p>',
		'photo' => 'paul.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'William Benett',
		'title' => 'Associate Professor',
		'area' => 'Sculpture',
		'school' => 'MFA Indiana University, 1975',
		'email' => 'whb@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'bennett.jpg',
		'link' => 1,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Sarah Betzer',
		'title' => 'Associate Professor',
		'area' => 'Eighteenth- and Nineteenth-Century European Art;<br>Feminist and Critical Theory',
		'school' => 'PhD Northwestern University, 2003',
		'email' => 'pb4r@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'bio-alternate-link' => HOME . 'betzer/',
		'photo' => 'placeholder.jpg',
		'link' => 0,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Daniel Bluestone',
		'title' => 'Associate Professor',
		'area' => 'American Architecture and Urbanism',
		'school' => 'PhD University of Chicago, 1984',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => false,
		'studio-art' => false
	),
	array(
		'name' => 'Bruce Boucher',
		'title' => 'Affiliated Faculty and Director, The Fralin Museum of Art',
		'area' => 'Italian Renaissance and Baroque Sculpture and Architecture',
		'school' => 'PhD Courtauld Institute of Art, University of London, 1987',
		'email' => 'bab8sa@eservices.virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'bio-alternate-link' => 'http://www.virginia.edu/artmuseum/about/staff/bios/#boucher',
		'link' => 0,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Cammy Brothers',
		'title' => 'Associate Professor',
		'area' => 'Italian Renaissance Architecture',
		'school' => 'PhD Harvard University, 1999',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Sheila Crane',
		'title' => 'Associate Professor',
		'area' => 'Modern Architecture and Urbanism',
		'school' => 'PhD Northwestern University, 2001',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Anastasia Dakouri-Hild',
		'title' => 'Lecturer',
		'area' => 'Greek and Near Eastern Art and Archaeology',
		'school' => 'PhD Archaeology/Classics; University of Cambridge, U.K., 2004',
		'email' => 'ad9h@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'bio-alternate-link' => HOME . 'dakouri-hild/',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Dean Dass',
		'title' => 'Professor',
		'area' => 'Printmaking',
		'school' => 'MFA Tyler School of Art, Temple University, 1980',
		'email' => 'dad@cms.mail.virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'dean.jpg',
		'link' => true,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'John J. Dobbins',
		'title' => 'Professor',
		'area' => 'Roman Art and Archaeology',
		'school' => 'PhD University of Michigan, 1977',
		'email' => 'jjd5t@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'john.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Daniel Ehnbom',
		'title' => 'Associate Professor',
		'area' => 'South Asian Art',
		'school' => 'PhD University of Chicago, 1984',
		'email' => 'dje6r@virginia.edu',
		'bio' => '<p>Daniel Ehnbom is the author of <i>Indian Miniatures: The Ehrenfeld Collection</i> (1985), articles on painting and Indian architecture, and contributions to various exhibition catalogues. He was with the Macmillan/Grove Dictionary of Art (1996) in London as a contributor and consultant from 1984 and as South Asia Area Editor for Painting and Sculpture from 1988. His most recent publications is the essay "Masters of the Dispersed Bhagavata Purana", in Milo C. Beach; Eberhard Fischer, B.N. Goswamy, eds, <i>Masters of Indian Painting: 1100-1900</i> (Z&uuml;rich: Artibus Asiae Publishers, Supplementum 48, I/II, 2011), volume 1, pp. 77-88. Mr. Ehnbom teaches undergraduate survey lecture courses on Indian and Islamic art, and upper level undergraduate lecture courses and undergraduate and graduate seminars in specialized topics including 16th-century Indian painting; early Indian sculpture and architecture; and architecture, sculpture, and painting of the Gupta Period. He is adjunct curator of South Asian art at the University of Virginia Art Museum, and Director of the UVA Center for South Asian Studies. He has held fellowships from Fulbright, the American Institute of Indian Studies, the American Council of Learned Societies, the Weedon Foundation, the UVA Shannon Center, and the UVA Teaching Technology Initiative project. </p>',
		'photo' => 'ehnbohm.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Kevin Everson',
		'title' => 'Associate Professor',
		'area' => 'Film',
		'school' => 'MFA Ohio University, 1990 ',
		'email' => 'ke5d@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'everson.jpg',
		'link' => true,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Francesca Fiorani',
		'title' => 'Associate Professor and Chair',
		'area' => 'Renaissance Art, Science and Visual Culture',
		'school' => 'PhD University of Rome "La Sapienza," 1994',
		'email' => 'ff6f@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'bio-alternate-link' => 'http://faculty.virginia.edu/Fiorani/',
		'urls' => array(
			array(
				'title'=>'Site >',
				'url'=>'http://faculty.virginia.edu/Fiorani/'
			)
		),
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Douglas Fordham',
		'title' => 'Associate Professor',
		'area' => 'British Art, Visual Culture of Empire, Eighteenth Century Art',
		'school' => 'PhD Yale University, 2003',
		'email' => 'df2p@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'fordham.jpg',
		'bio-alternate-link' => HOME . 'fordham/',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Phil Geiger',
		'title' => 'Professor',
		'area' => 'Painting / Drawing',
		'school' => 'MFA Yale University, 1980',
		'email' => 'png@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'phil.jpg',
		'link' => 1,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Lawrence O. Goedde',
		'title' => 'Professor',
		'area' => 'Baroque Art',
		'school' => 'PhD Columbia University, 1984',
		'email' => 'log@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'larry.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Carmenita Higginbotham',
		'title' => 'Associate Professor',
		'area' => 'American Art',
		'school' => 'PhD University of Michigan, 2005',
		'email' => 'ch6sv@cms.mail.virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'carmen.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Yunsheng Huang',
		'title' => 'Associate Professor',
		'area' => 'East Asian Art and Architecture',
		'school' => 'PhD Princeton University, 1986',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Susan Johnson-Roehr',
		'title' => 'ACLS New Faculty Fellow',
		'area' => 'History of South Asian Architecture and Science',
		'school' => 'PhD University of Illinois, 2011',
		'email' => 'snj2k@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'bio-alternate-link' => HOME . 'johnson-roehr/',
		'link' => false,
		'art-history' => 1,
		'phd' => false, 
		'studio-art' => false
	),
	array(
		'name' => 'Shiqiao Li',
		'title' => 'Weedon Professor',
		'area' => 'Modern and Contemporary Architecture',
		'school' => 'PhD University of London, 2006',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Maurie McInnis',
		'title' => 'Professor',
		'area' => 'American Art and Material Culture',
		'school' => 'PhD Yale University, 1996',
		'email' => 'mdm6n@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Megan Marlatt',
		'title' => 'Professor',
		'area' => 'Painting',
		'school' => 'MFA Rutgers University, 1986',
		'email' => 'mmg6n@cms.mail.virginia.edu',
		'bio' => '<a href="http://www.meganmarlatt.com/" target="_blank">Website ></a>',
		'photo' => 'megan.jpg',
		//'bio-alternate-link' => 'http://www.meganmarlatt.com/',
		'urls' => array(
			array(
				'title'=>'Artist Site >',
				'url'=>'http://www.meganmarlatt.com/'
			), 
			array(
				'title'=>'Big Head Brigade >',
				'url'=>'http://www.bigheadbrigade.com/'
			)
		),
		'link' => true,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Lydia Moyer',
		'title' => 'Associate Professor',
		'area' => 'Studio Media',
		'school' => 'MFA University of North Carolina Chapel Hill, 2005',
		'email' => 'lmoyer@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'moyer.jpg',
		'link' => 1,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Fraser D. Neiman',
		'title' => 'Lecturer',
		'area' => 'Director of Archaeology, Monticello',
		'school' => 'PhD Yale University, 1990',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => false,
		'studio-art' => false
	),
	array(
		'name' => 'Louis P. Nelson',
		'title' => 'Associate Professor',
		'area' => 'American and Caribbean Architecture',
		'school' => 'PhD University of Delaware, 2001',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Pamela Pecchio',
		'title' => 'Assistant Professor',
		'area' => 'Photography',
		'school' => 'MFA Yale University School of Art, 2001',
		'email' => 'pjp8p@Virginia.EDU',
		'bio' => 'Bio forthcoming.',
		'photo' => 'pecchio.jpg',
		'link' => 1,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Eric Ramirez-Weaver',
		'title' => 'Assistant Professor',
		'area' => 'Medieval Art',
		'school' => 'PhD New York University, 2008',
		'email' => 'emr6m@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'eric.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Lisa Reilly',
		'title' => 'Associate Professor',
		'area' => 'Medieval Art and Architecture',
		'school' => 'PhD New York University, 1990',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Akemi Ohira Rollando',
		'title' => 'Associate Professor',
		'area' => 'Printmaking/Drawing',
		'school' => 'MFA Carnegie Mellon University, 1992',
		'email' => 'ao9s@virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'akemi.jpg',
		'link' => true,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Elizabeth Schoyer',
		'title' => 'Lecturer  ',
		'area' => 'Drawing',
		'school' => 'MFA Indiana University, 1975',
		'email' => 'eps5u@virginia.edu',
		'bio' => '<p>Elizabeth Schoyer has taught beginning and advanced drawing at the University of Virginia for 25 years. As drawing concepts have broadened, her methods for teaching drawing have changed to encompass varying materials with the medium now standing more on its own as an art form. Drawing is a language in which line, marks, and space have their formal meaning as well as individual symbolisms that can transform expressions. It provides us with myriad possibilities for constructing images, allowing the student to stumble along into places he or she might not approach in other media. These possibilities leave the student freer and more vulnerable to create a personal vision through a drawing project. Some of the projects Schoyer uses to facilitate expressions of her students\' personal visions are: drawing performances using language, mapping as a vehicle to describe a personal history of moving through the landscape over time, or drawing totem animals to talk about one\'s emotional or physical history.</p><p>In her own work as an artist, Schoyer combines pencil drawing and oil painting washes on the canvas. These images relate to explorers of the 1700 and 1800 and their exploitation of various regions of the world.  Her recent work focuses on the Spanish explorer Jose Celestino Mutis, who established the Royal Botanical Expedition in 1783 to study the flora and fauna of South America. At its helm for 25 years he oversaw the collection of thousands of samples together with detailed descriptions. More than 8,000 plates, plus maps, correspondence, notes and manuscripts were sent to Spain.</p>',
		'photo' => 'elizabeth.jpg',
		'link' => 1,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	),
	array(
		'name' => 'Tyler Jo Smith',
		'title' => 'Associate Professor',
		'area' => 'Greek Art and Archaeology',
		'school' => 'D.Phil. Oxford University, 1997',
		'email' => 'tjs6e@virginia.edu',
		'bio' => 'smith.php',
		'bio-include' => true,
		'photo' => 'placeholder.jpg',
		'bio-alternate-link' => HOME . 'smith/',
		'link' => 1,
		'art-history' => 1,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Susan Stein',
		'title' => 'Lecturer<br>Curator, Monticello',
		'area' => 'American Studies',
		'school' => 'M.A. University of Chicago, 1977',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => false,
		'studio-art' => false
	),
	array(
		'name' => 'J. David Summers',
		'title' => 'Wm. R Kenan Jr. Professor',
		'area' => 'Art Theory and Italian Renaissance Art',
		'school' => 'PhD Yale University, 1969',
		'email' => '',
		'bio' => 'Bio forthcoming.',
		'photo' => 'david.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => false,
		'studio-art' => false
	),
	array(
		'name' => 'Elizabeth Hutton Turner',
		'title' => 'University Professor',
		'area' => 'Modern Art',
		'school' => 'PhD University of Virginia, 1985',
		'email' => 'eht5va@virginia.edu',
		'bio' => 'turner.php',
		'bio-include' => true,
		'photo' => 'turner.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => false,
		'studio-art' => false
	),
	array(
		'name' => 'Richard Guy Wilson',
		'title' => 'Commonwealth Professor',
		'area' => 'American Architecture',
		'school' => 'PhD University of Michigan, 1972',
		'email' => 'emailaddress',
		'bio' => 'Bio forthcoming.',
		'photo' => 'placeholder.jpg',
		'link' => false,
		'art-history' => 0,
		'phd' => true,
		'studio-art' => false
	),
	array(
		'name' => 'Dorothy Wong',
		'title' => 'Associate Professor',
		'area' => 'East Asian Art',
		'school' => 'PhD Harvard University, 1995',
		'email' => 'dcw7a@cms.mail.virginia.edu',
		'bio' => 'Bio forthcoming.',
		'photo' => 'wong.jpg',
		'link' => 1,
		'art-history' => 1,
		'phd' => false,
		'studio-art' => false
	),
	array(
		'name' => 'William Wylie',
		'title' => 'Professor and Associate Chair',
		'area' => 'Photography',
		'school' => 'MFA University of Michigan, 1989 ',
		'email' => 'ww9b@Virginia.EDU',
		'bio' => 'Bio forthcoming.',
		'photo' => 'wylie.jpg',
		'link' => 1,
		'art-history' => false,
		'phd' => false,
		'studio-art' => true
	)

);

?>