
E. Luanne McKinnon
MFA, Painting, TCU, Fort Worth, TX<br>PhD candidate
elmr55@earthlink.net
<p>Electra Luanne McKinnon studied extensively with the late Picasso scholar Lydia Gasman. Following her status as ABD/PhD in 2000 under the direction of David Summers and Howard Singerman, she lived in Scotland and was Lecturer for &ldquo;Re-reading Modern Art: 1900-1940&rdquo; at the Edinburgh College of Art, and visiting lecturer at the Scottish National Gallery of Modern Art. Returning to America in 2005, she served as the Bruce A. Beal Director of the Cornell Fine Arts Museum at Rollins College; and, from 2009-2012, as Director of the University of New Mexico Art Museum. She curated or organized over twenty-six exhibitions, and contributed to or authored nine publications including, <em>Eva Hesse Spectres 1960</em>; <em>James Turrell&rsquo;s Emblemata</em>; <em><a href="http://www.amazon.com/Tamarind-Touchstones-Fabulous-Excellence-Lithography/dp/0826347401/ref=sr_1_1?ie=UTF8&amp;qid=1386021648&amp;sr=8-1&amp;keywords=tamarind+at+50" target="_blank">Tamarind Touchstones: Creating Excellence in Fine Art Lithography</a></em>; <em><a href="http://www.amazon.com/To-Form-Air-Raymond-Jonson/dp/0890135711/ref=sr_1_1?ie=UTF8&amp;qid=1386021678&amp;sr=8-1&amp;keywords=raymond+jonson+form+to+air" target="_blank">To Form from Air, Music and the Art of Raymond Jonson</a></em>; <em>Corps Exquis: Fragments from a History of the Human Body, 1585 to 2005; </em>and, <em>Crossing the Line, African American Artists in the Bradley Otis Collection.</em> Other notable curatorial projects: <em>Man Ray, African Art and the Modernist Lens;</em> <em>Hiroshi Sugimoto, Five Campaigns</em>; <em>The Infernal Method of William Blake; Nevelson by Night; Nick Cave Sound Suits; Winslow Homer Joys of the Day; Henri Matisse&rsquo;s &lsquo;Jazz;&rsquo; Richard Deacon / &ldquo;Dead Leg&rdquo;; and,</em> <em>Reconsidering the Photographic Masterpiece.</em>In her capacity as museum director, she organized symposia and distinguished lectures with Briony Fer, Barbara Maria Stafford, Lowry Sims, Dave Hickey, Anne Collins Goodyear, and the artists Ed Ruscha, Fred Wilson, Lyle Ashton Harris, Richard Deacon, Jim Campbell, Jerry Uelsmann, and Daniel Reeves, among others.</p>

Elizabeth Merrill
BA, Art and Architectural History, Columbia University, 2007 <br>MA, Art and Architectural History, University of Virginia, 2010 <br>PhD candidate
emm2z@virginia.edu
<p>Elizabeth studies Italian Renaissance art and architecture with Professor Cammy Brothers. She received her Bachelor\'s degree in Art and Architectural History from Columbia University in 2007 and completed her Master\'s degree at UVA in 2010. Her MA thesis examined the Villa dei Vescovi (Padua, c. 1535) as a restitution of the ancient Roman domus. Elizabeth&rsquo;s dissertation focuses on the multifaceted career of the Sienese architect Francesco di Giorgio Martini in relation to the development of the architectural profession. She has published an article related to her thesis in the peer-reviewed <em>Architectural Histories Journal</em> (Fall 2013). Elizabeth has also has served as a teaching assistant for multiple undergraduate courses on art and architecture for UVA in Charlottesville and abroad. In spring 2012, she taught an undergraduate seminar on Italian Renaissance court architecture. Her research has been supported by the Renaissance Society of America (Rensselaer W. Lee Memorial Grant, 2011), the Buckner W. Clay Endowment for the Humanities (2012), the UVA-Humboldt Universit&auml;t Graduate Fellowship (2012-2013), the Morgan Library and Drawing Institute (2013), and the Thomas Jefferson Memorial Foundation (Dumas Malone Research Fellowship, 2013-2014).</p>

Katherine Ann Miller
BA, Art History, University of Southern California, 2006<br>MArchH, University of Virginia, 2010<br>PhD candidate
kam8wr@virginia.edu
<p>Kat Miller is fourth-year doctoral candidate studying American architecture and art with Professor Richard Guy Wilson. Her research interests include public architecture, the professionalization of architecture in early America, the business of architecture, architectural photography, and architectural representation. </p><p>Kat&rsquo;s dissertation, "The Office of the Supervising Architect in the Antebellum Era: Transforming Architectural Practice, 1852-1862," examines Ammi B. Young\'s tenure as supervising architect at the U.S. Department of Treasury. It demonstrates that Young introduced innovations in building technology and architectural representation that helped establish the first systematized building program in America. Looking at federal customhouses built in New England and the South on the eve of the Civil War, the study looks at how the Office negotiated architectural authority over local sites. This research closely examines the letters, drawings, lithographed working drawings, and construction photographs produced by the Office&rsquo;s architect, engineer, draftsman, lithographer and photographer. The dissertation exposes how new standardized national architectural practices were communicated to local builders.</p><p>Kat&rsquo;s research is supported by fellowships from the U.S. Capitol Historical Society and the Lindner Center for Art History at the University of Virginia. Her dissertation has been supported by a research grant from the University of Virginia&rsquo;s School of Architecture and a Raven Society scholarship. Her dissertation topic emerged from a research fellowship with the Department of Treasury&rsquo;s Office of the Curator in 2010 and was refined through a scholarship to attend Historic New England&rsquo;s Program in New England Studies in 2012.</p>

Elizabeth M. Molacek
BA, Art History, Rice University, 2007<br>MA, History of Art and Architecture, University of Virginia, 2010<br>PhD candidate
elizabeth.molacek@virginia.edu
<p>Elizabeth Molacek is a doctoral candidate studying ancient Roman art and architecture. Her dissertation, &ldquo;Observing, Reflecting, Interacting: Imagining a Viewer in Roman Wall Paintings,&rdquo; considers mythological wall paintings as locations of convergence between the internal viewers and the external audience that communicate meaning and response. Elizabeth also works on mosaic pavements resulting in her publication &ldquo;Narcissus the Hunter in the Mosaics of Antioch,&rdquo; <em>Athanor XXXI </em>(2013). She also works on ancient jewelry and as a curatorial intern at the Virginia Museum of Fine Arts she conducted research on the museum&rsquo;s collection of ancient Greek and Roman jewelry and gems. On a separate occasion, she was a research intern in the Contemporary Art Department assisting with the 2010 exhibit &ldquo;Sally Mann: the Flesh and the Spirit.&rdquo; In summer 2009 she participated in the American Academy in Rome&rsquo;s Summer Program in Archaeology and during the same summer she participated in excavations with the University of Cincinnati&rsquo;s Pompeii Archaeological Research Project: Porta Stabiae (PARP:PS).</p><p>At UVA Elizabeth has taught in various capacities in the McIntire Department of Art; developed and taught a course for the Curry School of Education&rsquo;s Summer Enrichment Program; and served as a teaching assistant for UVA&rsquo;s Semester at Sea. Since 2011, Elizabeth has served as a Coordinator of Studies at the University&rsquo;s Hereford Residential College where she engages with students in academic and mentoring roles.</p><p><a href="www.about.me/elizabeth_molacek" target="_blank" class="indent">Web site ></a></p>

Murad Khan Mumtaz
BFA, National College of Arts, Lahore, Pakistan, 2004<br>MFA, Visual Arts, Columbia University, 2010<br>PhD student
mkm9na@virginia.edu
<p>A native of Lahore, Murad is a graduate student in the Art History Department studying South Asian art with a focus on Indian painting. His interest in North Indian painting traditions grows out of his practice as an artist trained in Mughal techniques. Prior to pursuing PhD study, he completed an MFA from Columbia University, which he attended on a Fulbright Fellowship. He has exhibited his work internationally and is represented by Tracy Williams, Ltd., in New York.</p><p>His research focuses on the history of materials and techniques in North Indian painting, with a special focus on traditional pigments. His recent interests have also expanded into studying 18<sup>th</sup>- and 19<sup>th</sup>-century painting from Punjab, considering both the materiality of the artworks as well as the socio-cultural context of their production.</p><p>He has written extensively on the relationship between contemporary miniature painting practice and its traditional precedents. Recent publications include &ldquo;Miniature Painting in Pakistan: Divergences Between Traditional and Contemporary Practice,&rdquo; written for the<em>Guggenheim Global Art Initiative</em> (February 2013), and &ldquo;Reconciling Tradition and Contemporary Practice in Present Day Miniature Painting in Pakistan,&rdquo; <em>Hand Papermaking Magazine</em> (Winter 2012).</p>

Jennifer Stettler Parsons
BA, Art History, University of Delaware, 2006<br>MA, Art History, George Washington University, 2008<br>PhD candidate
jas6ss@virginia.edu
<p>Jenny studies modern American and European art under the direction of Elizabeth Hutton Turner. Her research interests include the development of modernism in America, visual and material culture, transatlantic dialogue, and regional identities.</p><p>Her dissertation, &ldquo;John Sloan: Between Philadelphia and New York, 1892-1907,&rdquo; examines the importance of place and regional artistic networks in the early work of John Sloan. It concentrates on Sloan&rsquo;s Philadelphia works in diverse media to explore the degree to which his art and artistic identity were shaped by his complicated shift between Philadelphia and New York.</p><p>Before coming to UVA, Jenny worked at the Philadelphia Museum of Art where she held several positions, including a research assistantship for the <em>Calders on the Parkway</em> program. She has interned at the National Gallery of Art, Washington, D.C., the Phillips Collection, the Delaware Art Museum, and the University Museums at the University of Delaware. At UVA, she was a teaching assistant for Art Since 1945 and Art History II, and served as a graduate research assistant.</p><p>Jenny won the 2012 Graduate Research Essay Prize from the Smithsonian&rsquo;s Archives of American Art for her essay, &ldquo;Absence and Presence: Arthur Dove&rsquo;s Paintings &lsquo;From the Radio.&rsquo;&rdquo; It is published online: <a href="http://www.aaa.si.edu/essay/jennifer-parsons" target="_blank">http://www.aaa.si.edu/essay/jennifer-parsons</a></p><p>As the 2013-14 Barra Fellow in American Art, Jenny is currently in residence at the Center for American Art at the Philadelphia Museum of Art.</p>

Corey Piper
BA, Art History, University of South Carolina<br>MA, Art History, Virginia Commonwealth University
csp7q@virginia.edu
<p>Corey studies nineteenth-century American art. He wrote his  MA thesis on the Pittsburgh artist David Gilmour Blythe, examining his street urchin scenes in the context of nativist political and social movements of the antebellum period. Corey previously served as a curatorial associate at the Virginia Museum of Fine Arts in the Mellon and European departments and recently completed a summer fellowship at the Center for American Art at the Philadelphia Museum of Art. He has curated or co-curated several exhibitions including<em>George Morland: Poet of English Country Life,</em> <em>Scraps: British Sporting Drawings from the Paul Mellon Collection</em> and <em>Catching Sight: The World of the British Sporting Print</em> and has published research on Currier and Ives lithographs, Georgian portraiture, and the social history of British sporting prints.</p>

Emily Caplan Reed
BA, History of Art and Architecture, Harvard College, 2004<br>MA, History of Art and Architecture, University of Chicago, 2007<br>PhD candidate
ecr5m@virginia.edu
<p>Emily Caplan Reed studies modern American and European sculpture. She is writing a doctoral dissertation titled "Alexander Calder, Naum Gabo, Isamu Noguchi and the Pre- and Post-War Development of Abstract Art for Public Space," under the direction of Elizabeth Hutton Turner. She is particularly interested in these artists\' collaborations with architects, patrons and engineers, before and after the Second World War. Her other research interests include the history of museums, commissions, and site-specific art.</p><p>Prior to matriculating at the University of Virginia, Emily worked at Thomas Jefferson&rsquo;s Monticello in Charlottesville, Virginia, and held an internship at the National Portrait Gallery in Washington, D.C.</p><p>Emily is originally from Seattle, Washington. Her grandfather was a prominent Pacific Northwest artist, and her family inspired her study of the visual arts.</p>

Dylan Rogers
BA, Classical Studies, Italian and Greek, Tulane University, 2008<br>MA, History of Art and Architecture, University of Virginia, 2010<br>PhD candidate
dkr5t@virginia.edu
<p>Currently a PhD candidate, Dylan\'s dissertation, &ldquo;Water-Display and Meaning in the High Roman Empire,&rdquo; seeks to understand the reasons why the Romans displayed water. By using available archaeological evidence of Roman fountains throughout the Empire, the study attempts to discern patterns in water-display, such as regional differences, along with thematic uses of water (e.g., domestic, political, religious, and social). Dylan completed fieldwork for the dissertation in Spain and Portugal during the summer of 2013. In addition, he will complete research as a Regular Member of the American School of Classical Studies at Athens during the 2013-2014 academic year.</p><p>Dylan\'s fieldwork experience includes Pompeii (<a href="http://classics.uc.edu/pompeii/" target="_blank">Porta Stabiae Project</a>, 2009), Hacimusalar H&ouml;y&uuml;k, Turkey (Bilkent University, 2011, 2012), and Morgantina (Princeton/UVA, 2011). Dylan has been a teaching assistant in the Art, Classics, and History departments at UVA.</p><p>Major research interests of Dylan include the display of water, Roman domestic religion, Roman gardens, the topography of the city of Rome, and the reception of Antiquity from the Renaissance through the modern period; other research interests outside of Classical Archaeology include Medieval Rome and Italy, including the twelfth century pavements of Cappella Palatina in Palermo, on which Dylan is currently writing an article.</p><p><a href="http://dylankrogers.wordpress.com/" target="_blank" class="indent">Web site ></a></p>

Sean Tennant
BA, History, George Mason University, 2009<br>MA, History of Art and Architecture, University of Virginia, 2013
st2bz@virginia.edu
<p>Sean\'s research focuses on the interaction between the Romans and the Iron Age peoples along the Germanic frontier of the Roman Empire. Aspects of military action, colonization, and identity are central to this research. Sean has excavated at the site of Morgantina in Sicily, serving as an assistant supervisor in 2013. Prior to attending the University, Sean was an archaeologist working on Colonial period sites in northern Virginia.</p>

Edward P. Triplett
BA, History and Photography, University of Delaware, 2001<br>MFA, 3D Graphics and Animation, Savannah College of Art and Design, 2004<br>MA, History, Certificate in Museum Studies, 2007<br>MA, Architectural History, University of Virginia, 2009<br>PhD candidate
Edward.triplett@gmail.com
<p>Edward Triplett is a doctoral candidate studying Medieval Architecture. His dissertation, &ldquo;Architectural Reconquest: The Fortified Presence of Military Orders on the Iberian Border with Islam&rdquo; establishes sight-lines as signifiers of architectural intention by running outward and inward-facing viewshed analyses at a sub-set of Iberian fortress-monasteries. With the assistance of two years of fellowship support from the UVA&rsquo;s &ldquo;Scholars&rsquo; Lab&rdquo; Edward created a custom GIS database containing over 300 architectural sites built or occupied by military orders in 12<sup>th</sup>-14<sup>th</sup> century Iberia, as well as two 3D models derived from photogrammetry data processed from over 30 thousand digital photographs taken at the fortress-monasteries of Calatrava la Nueva and Montesa. He has worked as a visualization specialist at UVA&rsquo;s Institute for Advanced Technology in the Humanities (IATH) since his arrival in 2007, constructing interactive maps and 3D models for the Chaco Canyon, Southwell Minster, Virtual Williamsburg, Plan of St. Gall, Fort Snelling and Montpelier projects. In addition to the Scholars&rsquo; Lab Graduate Fellowship in Digital Humanities, Edward was an inaugural member of the Praxis Program &ndash; designed to teach programming and web-development skills to humanities graduate students &ndash; and received research grants from the Kress Foundation and the Dumas Malone research fellowship.</p><p>In addition to acting as a teaching assistant in the Art and Architectural History departments, Edward co-taught a course revealing digital methods for architectural recording and preservation, and has given guest lectures on broader digital humanities and architectural history topics. His recent freelance projects include a 3D reconstruction of Tusculum &ndash; a dismantled 18<sup>th</sup>-19<sup>th</sup> century plantation house owned by the original founders of Sweet Briar College in Amherst, VA&mdash; and a dense photogrammetric 3D model of a detached chimney for the joinery shop at Thomas Jefferson&rsquo;s Monticello.</p><p><a href="www.edwardtriplett.com" target="_blank" class="indent">Web site ></a></p>

Victoria Valdes
BA, Art History, Mary Washington, 2006<br>MA, History of Art and Architecture, University of Virginia, 2010<br>PhD candidate
vav6n@virginia.edu
<p>Victoria Valdes has been a member of the University of Virginia\'s graduate program in Art and Architectural history since 2008. As a Presidential Fellow, she developed her interest in female monastic practice and the art of the convent in her master\'s thesis, &ldquo;Women, Metalwork and the Frauenstift Essen in Ottonian Germany.&rdquo; She has served as a teaching assistant for a number of classes and in 2012 won the departmental award for outstanding performance as a teaching assistant.</p><p>Currently an ABD student, Victoria is working on a dissertation connecting Ottonian visual culture and the important role of courtly modalities of patronage cultivated by women for the creation of an Ottonian imperial identity. Her areas of expertise include metalwork and illuminated manuscripts of the tenth and eleventh centuries. Her work emphasizes the interrelation of visual works, literature and performance in the negotiation and establishment of power relationships.</p><p>In 2012, Victoria taught a lecture class in Art and Architectural History, "Age of Cathedrals," which explored late Romanesque and Gothic church building in the Middle Ages and associated works of art. She regularly teaches introductory Art History courses at Piedmont Virginia Community College. Victoria serves as 2013-14 Director of the Interdisciplinary Medieval Colloquium, and in 2013 she represented UVA on the <em>Exemplaria</em> interdisciplinary panel at Kalamazoo.</p>

Claire J. Weiss
BA, Biology, Swarthmore College, 2003<br>MA, Archaeology, Institute of Archaeology, University College London, 2007<br>PhD candidate
cjw9bs@virginia.edu
<p>Claire Weiss began her studies at Virginia in 2011, having received her Master&rsquo;s degree with distinction from the Institute of Archaeology at University College London (UCL) in 2007 under the supervision of Dr. Kathryn Lomas. At UCL, Claire&rsquo;s dissertation presented a GIS analysis of a feature of Pompeian sidewalks. Prior to this, Claire graduated from Swarthmore College in 2003 with a Bachelor&rsquo;s degree in Biology and a minor in Latin.</p><p>Claire has worked and supervised field excavation in Pompeii since 2001 and has served as the Project Coordinator for the <a href="http://www.viaconsolareproject.org/" target="_blank">Via Consolare Project</a> (VCP) in Pompeii since 2006. In this position, she oversees the administration of the Project, maintains the student internship application process, and supervises excavation in the field. In addition to her experience in Pompeii, Claire has worked in American Cultural Resource Management (CRM) excavation.</p>

Anne Williams
BA, History of Art, University of Virginia, 2008<br>MA. History of Art and Architecture, University of Virginia, 2011<br>PhD candidate
alw3b@virginia.edu
<p>Anne specializes in the art of late medieval and Renaissance northern Europe. Her doctoral dissertation, &ldquo;Sanctity and Satire: St. Joseph and Humor in Northern European Art, ca. 1300-1530,&rdquo; explores comic and satirical iconography in early modern paintings, sculpture, and prints of Saint Joseph. Relying on extant German and French Nativity and Shrovetide plays, late medieval <em>facetiae, fabliaux</em>,<em>Schwankliteratur, </em>and satirical paintings and prints, her work reveals the integral role of humor in establishing St. Joseph as an exemplar of the common man in Germany, the Low Countries, and northeastern France. Her writing and teaching have been supported by fellowships from the Dolores Zohrab Liebmann Fund, the Andrew W. Mellon Foundation, and the University of Virginia.</p>

Thomas M. Winters
BA, Art History, University of Utah, 2010<br>MA, Art History, University of Virginia, 2012<br>PhD candidate
tmw2kq@virginia.edu
<p>Tom Winters was born in the English Midlands and raised in North Wales, but has lived in the United States since 1997. He graduated from the University of Utah with a BA in Art History in May 2010. Tom&rsquo;s main area of focus as an undergraduate was Dutch art of the seventeenth century, with a senior seminar paper on the role of music in genre scenes, and a research project on the attribution of a landscape painting in the Utah Museum of Fine Arts.</p><p>In August 2010, Tom joined the graduate program in Art History at the University of Virginia with a Presidential Fellowship. Since that time he has continued his study of seventeenth-century Dutch art under the advisement of Professor Lawrence Goedde, while also exploring diverse topics in seminars on Medieval, Buddhist, Italian Renaissance, 18<sup>th</sup> and 19<sup>th</sup> Century, and Abstract Expressionist art, among others. In addition to his studies, Tom has greatly enjoyed and benefitted from his experiences as a teaching assistant for a variety of courses in Art History and Architectural History. In May 2012, Tom was awarded his MA in Art History after having completed a thesis entitled &ldquo;Flowers and Crooks, Feathers and Lutes: Gerrit van Honthorst&rsquo;s Erotic Fictive-Figure Painting.&rdquo; He regrets not having spent more time on the title.</p><p>Since completing his coursework in May 2013, Tom has begun work on his PhD dissertation, currently entitled &ldquo;Gerard van Honthorst and the Scopic Regime of the Dutch Golden Age.&rdquo;</p>